version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    # network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=9E-7vaQuhCBJJ1aLJ2xY
      - ADVERTISE_IP=http://192.168.1.3:32400/
    hostname: plexserver.example.com
    volumes:
      # - /path/to/library:/config
      - /Volumes/media/TV:/tv
      - /Volumes/media/Movie:/movies
    restart: unless-stopped
